#!/usr/bin/env ruby
require 'rubygems'
require 'dropio'
include Dropio

#
# Create a new drop and add files to it
#

#
# get your API key @ http://api.drop.io
#
Dropio.api_key = 'your_api_key_here'
admin_token = '0000000000'
drop_name = 'mydropname'

begin

  #
  # Drop can be named, or unnamed. The drop name
  # will be randomly generated by drop.io if :name option
  # is not specified
  #
  drop = Drop.create(
    { :expiration_length => '1_DAY_FROM_NOW',
      :guests_can_add => false,
      :guests_can_comment => false,
    }
  )
  drop.add_file('file_somewhere')

rescue Dropio::MissingResourceError
  puts 'Drop does not exist.'
rescue Dropio::AuthorizationError # no permissions to read the drop
  puts 'Not authorized.'
end
